### PR TITLE
Wildcard and Floors

### PR DESCRIPTION
**Pull request by kylegessel**
This is now a play-testable game! Before submitting this pull request, Brad was able to finish and complete the game.

This PR:
- Adds Wildcards
- Adds floor changes
- Implements the new bosses and rope snake
- Places the new shop at the end of each boss room
- Adds one compass, key and map per floor
- Creates a five floor random game!

Some early play-testing notes:
Honestly, watching brad play it felt easy. Personally, I thought some rooms felt too busy. the red background needs a little bit of a change. Too many enemies blend in with it.

Some ideas:
- enemies should hit harder in later floors
- enemies should drop less items
- Enemies could have more health (not my favorite solution)

There are still some major bugs. Some Rooms have enemies too close to the door. All HUDs need a little bit of love. The Hand is still not present in this edition of the code. Snakes can jump over water (Honestly, I think this is cool). Please test this and take notes. All we have left are bug fixes!

### CODE REVIEW

**Review by Bailey-Ardrey — APPROVED** [review]
Looks good Kyle!

**Comment by Bailey-Ardrey** [comment]
Very solid work. Thank you for taking a lead on this sprint!! Your generation of rooms is sweet!

**Comment by bradknez** [comment]
Thought I would add that the snakes can jump over water and outside of rooms, something to take a look at.

**Comment by bjhobson12** [comment]
I wrote a bunch of stuff but it got deleted... so I'm going to be concise. These are not all about this pr but things that are bad in general:

Pausing the game and restarting from screen resets hud to appear over player area.

Shop menu displays foreign rupee off screen and it stays put during room transition until it is flush with prices (prol just isnt being properly handled by the shop for transition).

Enter final boss room from right to left (facing behind dragon) in floor 1.

Roommate couldn't beat dongowhatevers floor2 because he didnt have bombs... maybe when the player gets to boss room they get 10 extra items of what they need.

The minimap blue tile thing in hud occassionally "races" and transitions at a double speed.

Items can be dropped by enemies over a brick, thus making them unreachable, even though the sword got them there.

Consider taking shop room off blue tile map.

The blue things that race after the player when they are intersecting him on an axis do so at any time instead of when he is only near edges of map. Therefore if I enter room from left to right then I might trigger the bottom left one to pop up and then go around it and walk down, but it will intersect with me again and attack me even when I am not at edges or room.

I keep fucking hitting the quit button and its not even funny...to be finished another time:)

**Pull request merged**
