### PR TITLE
Created Keyboard Manager

### PR DESCRIPTION
**Pull request by bjhobson12**
Sorry I need to stop editing master directly.

### CODE REVIEW

**Comment by kylegessel** [comment]
This is throwing an exception when I hit '1' '2', 'n' or 'z'. I think this needs a quick update.

**Comment by kylegessel** [comment]
This exception occurs ANY time any key is pressed that isn't registered. (registered keys are ones that control walk, damage, or cycling). Attack keys were not registered previously to ensure the entire animation played out, but the game shouldn't throw an exception if the user hits g accidentally.

**Comment by bjhobson12** [comment]
@kylegessel No exception any more with unregistered keys:)

**Comment by Bailey-Ardrey** [comment]
This looks great!! Game1 is much cleaner now.

I'll give others a little time to check it out, then I'll merge it a little later if there are no discrepancies.

**Pull request merged**
